QL_Tour_Du_Lich/QL_Tour_Du_Lich/Models/Tai_Khoan.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QL_Tour_Du_Lich.Models
{
    public class Tai_Khoan
    {
        [HiddenInput(DisplayValue =false)]
        public int Id { get; set; }
        [Required(ErrorMessage = "Vui lòng không để trống !")]
        [Display(Name = "Tên đăng nhập")]
        public string Ten_Dang_Nhap { get; set; }
        
        [Required(ErrorMessage = "Vui lòng không để trống !")]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Vui lòng không để trống !")]
        [DataType(DataType.Password)]
        [Display(Name = "Mật khẩu")]
        [MinLength(8,ErrorMessage ="Mật khẩu phải >=8 ký tự")]
        public string Mat_Khau { get; set; }
        [HiddenInput(DisplayValue =false)]
        public int Loai_Nguoi_Dung_Id { get; set; }
        public virtual Loai_Nguoi_Dung Loai_Nguoi_Dung { get; set; }
    }
}

QL_Tour_Du_Lich/QL_Tour_Du_Lich/Controllers/TaiKhoanController.cs
using QL_Tour_Du_Lich.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.Linq;
using System.Net.Mail;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace QL_Tour_Du_Lich.Controllers
{
    public class TaiKhoanController : Controller
    {
        // GET: TaiKhoan
        Context_Database db = new Context_Database();
        public ActionResult Index()
        {
            return RedirectToAction("DangNhap");
        }
        public ActionResult DangKy()
        {
            LoadDefaulData();
            return View();
        }
        [HttpPost]
        public ActionResult DangKy(Tai_Khoan tk)
        {
            LoadDefaulData();
            if (ModelState.IsValid)
            {
                try
                {
                    if (kiemtraTK(tk) == false)
                    {
                        string matkhau = MD5Hash(tk.Mat_Khau);
                        tk.Mat_Khau = matkhau;
                        tk.Loai_Nguoi_Dung_Id = 1;
                        db.Tai_Khoans.Add(tk);
                        db.SaveChanges();
                        return RedirectToAction("DangNhap", tk);
                    }
                    else
                    {
                        ViewBag.ThongBao = "Tên đăng nhập đã tồn tại hoặc email đã tồn tại";
                        return View(tk);
                    }
                }
                catch (Exception)
                {
                    return HttpNotFound();
                }
            }
            return View(tk);
        }
        public ActionResult DangNhap()
        {
            LoadDefaulData();
            Session["thongbao"] = "";
            return View(new Tai_Khoan());
        }
        [HttpPost]
        public ActionResult DangNhap(string Ten_Dang_Nhap, string Mat_Khau)
        {
            LoadDefaulData();
            if (ModelState.IsValid)
            {
                string matkhau = MD5Hash(Mat_Khau);
                if (kiemtraTkDN(Ten_Dang_Nhap, matkhau) == true)
                {
                    Tai_Khoan tk = getTaiKhoan(Ten_Dang_Nhap, matkhau);
                    Session["Email"] = tk.Email;
                    Loai_Nguoi_Dung loai = db.Loai_Nguoi_Dungs.Find(tk.Loai_Nguoi_Dung_Id);
                    if (loai.Ten_Loai.Equals("Admin"))
                    {
                        Session["adminlogin"] = true;
                        Session["emailadminlogin"] = tk.Email;
                        return RedirectToAction("Index", "Admin");
                    }
                    else
                    {
                        return RedirectToAction("Index", "HomeLogin");
                    }
                }
                else
                {
                    Session["thongbao"] = "";
                    ViewBag.ThongBao = "Tài khoản hoặc mật khẩu không chính xác";
                    return View();
                }
            }
            return View();
        }
        public ActionResult QuenMatKhau()
        {
            LoadDefaulData();
            Session["loaixacnhan"] = "resetmk";
            return View();
        }
        [HttpPost]
        public ActionResult QuenMatKhau(string emailaddress)
        {
            LoadDefaulData();
            if (emailaddress != "")
            {
                LoadDefaulData();
                Session["Ma"] = randomMa();
                Session["emailreset"] = emailaddress;
                Tai_Khoan tk = db.Tai_Khoans.Where(x => x.Email.Equals(emailaddress)).FirstOrDefault();
                if (tk != null)
                {
                    sendMail(emailaddress, "Reset mật khẩu từ Easy tour booking", "Mã xác nhận của bạn là: " + (string)Session["Ma"]);
                    Session["thongbao"] = "Mã xác nhận đã được tới email của bạn";
                    return RedirectToAction("XacNhan");
                }
                else
                {
                    ViewBag.ThongBao = "Email này chưa được đăng ký";
                    return View();
                }
            }
            ViewBag.ThongBao = "Bạn chưa nhập địa chỉ email";
            return View();

        }
        public ActionResult XacNhan()
        {
            try
            {
                LoadDefaulData();
                if (Session["loaixacnhan"].ToString().Equals("resetmk"))
                {
                    Session["ValueButton"] = "Lấy mật khẩu";
                    return View();
                }
                if (Session["loaixacnhan"].ToString().Equals("dattour"))
                {
                    Session["ValueButton"] = "Xác nhận";
                    return View();
                }
            }
            catch (Exception) { return HttpNotFound(); }

            return View();
        }
        [HttpPost]
        public ActionResult XacNhan(string xacnhan)
        {
            LoadDefaulData();
            if (xacnhan != "")
            {
                string ma = (string)Session["Ma"];
                if (xacnhan.Equals(ma.Trim()))
                {
                    if (Session["loaixacnhan"].ToString().Equals("resetmk"))
                    {
                        string email = (string)Session["emailreset"];
                        Tai_Khoan tk = db.Tai_Khoans.Where(x => x.Email.Equals(email)).FirstOrDefault();
                        tk.Mat_Khau = MD5Hash("12345678");
                        db.Entry(tk).State = EntityState.Modified;
                        db.SaveChanges();
                        Session["thongbaoreset"] = "Mật khẩu mới của bạn là: 12345678";
                        return RedirectToAction("DangNhap");
                    }
                    if (Session["loaixacnhan"].ToString().Equals("dattour"))
                    {
                        Chi_Tiet_Hoa_Don hd = (Chi_Tiet_Hoa_Don)Session["hoadonsendmail"];
                        Chi_Tiet_Hoa_Don ct = db.Chi_Tiet_Hoa_Dons.Find(hd.Id);
                        ct.Trang_Thai = "Xác nhận";
                        db.Entry(ct).State = EntityState.Modified;
                        db.SaveChanges();
                        ViewBag.ThongBao = "Xác nhận đơn hàng thành công";
                        string body = "Đơn hàng đã được xác nhận. Nếu có bất kỳ sự thay đổi nào vui lòng liên lệ Hotline (0397611751) để được hỏ trợ";
                        string subject = "Xác nhận đơn hàng từ Easy tour booking";
                        sendMail(ct.Email, subject, body);
                        return RedirectToAction("Index");
                    }
                }
                else
                {
                    Session["thongbao"] = "";
                    ViewBag.ThongBao = "Mã xác nhận không đúng";
                    return View();
                }

            }
            Session["thongbao"] = "";
            ViewBag.ThongBao = "Bạn chưa nhập mã xác nhận";
            return View();
        }
        private Tai_Khoan getTaiKhoan(string ten, string mk)
        {
            Tai_Khoan tk = db.Tai_Khoans.Where(x => x.Ten_Dang_Nhap.Equals(ten) && x.Mat_Khau.Equals(mk)).FirstOrDefault();
            return tk;
        }
        private bool kiemtraTkDN(string ten, string mk)
        {
            foreach (var x in db.Tai_Khoans.ToList())
            {
                if (x.Ten_Dang_Nhap.Equals(ten) && x.Mat_Khau.Equals(mk))
                    return true;
            }
            return false;
        }
        private bool kiemtraTK(Tai_Khoan tk)
        {
            foreach (var x in db.Tai_Khoans.ToList())
            {
                if (x.Ten_Dang_Nhap.Equals(tk.Ten_Dang_Nhap) || x.Email.Equals(tk.Email))
                    return true;
            }
            return false;
        }
        private static string MD5Hash(string input)
        {
            StringBuilder hash = new StringBuilder();
            MD5CryptoServiceProvider md5provider = new MD5CryptoServiceProvider();
            byte[] bytes = md5provider.ComputeHash(new UTF8Encoding().GetBytes(input));

            for (int i = 0; i < bytes.Length; i++)
            {
                hash.Append(bytes[i].ToString("x2"));
            }
            return hash.ToString();
        }
        private void sendMail(string email, string subject, string body)
        {
            try
            {
                string from = ConfigurationManager.AppSettings["email"];
                string pass = ConfigurationManager.AppSettings["password"];
                SmtpClient client = new SmtpClient();
                client.Port = 587;
                client.Host = "smtp.gmail.com";
                client.EnableSsl = true;
                client.Timeout = 10000;
                client.DeliveryMethod = SmtpDeliveryMethod.Network;
                client.UseDefaultCredentials = false;
                client.Credentials = new System.Net.NetworkCredential(from, pass);

                MailMessage mm = new MailMessage(from, email, subject, body);
                mm.BodyEncoding = UTF8Encoding.UTF8;
                mm.IsBodyHtml = true;
                mm.DeliveryNotificationOptions = DeliveryNotificationOptions.OnFailure;

                client.Send(mm);
            }
            catch (Exception)
            {
                ViewBag.ThongBao = "Không gửi được mail";
            }
        }
        private string randomMa()
        {
            string UpperCase = "ABCDEFGHJKLOIUYZCMNVN";
            string LowerCase = "abcdefghijklmnopqxyzs";
            string Digits = "1234567890";
            string allCharacters = UpperCase + LowerCase + Digits;
            Random r = new Random();
            string xacnhan = "";
            for (int i = 0; i < 6; i++)
            {
                double rand = r.NextDouble();
                if (i == 0)
                {
                    xacnhan += UpperCase.ToCharArray()[(int)Math.Floor(rand * UpperCase.Length)];

QL_Tour_Du_Lich/QL_Tour_Du_Lich/Views/TaiKhoan/DangKy.cshtml
@model QL_Tour_Du_Lich.Models.Tai_Khoan

@{
    ViewBag.Title = "Đăng ký tài khoản";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    #tuade{
        text-align:center
    }
    #thongbao{
        color:red;
    }
</style>
<h2 id="tuade">Đăng ký</h2>
<hr />
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Ten_Dang_Nhap, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ten_Dang_Nhap, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ten_Dang_Nhap, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mat_Khau, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mat_Khau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mat_Khau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <h4 id="thongbao">@ViewBag.ThongBao</h4>
                <input type="submit" value="Đăng ký" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <a href="/Home/Index">Trở về</a>
</div>

QL_Tour_Du_Lich/QL_Tour_Du_Lich/Views/TaiKhoan/DangNhap.cshtml
@model QL_Tour_Du_Lich.Models.Tai_Khoan

@{
    ViewBag.Title = "Đăng nhập";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    #tuade{
        text-align:center;
    }
    #thongbao{
        color:red;
    }
</style>
<h2 id="tuade">Đăng nhập</h2>
<hr />
@using (Html.BeginForm("DangNhap","TaiKhoan",FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Ten_Dang_Nhap, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ten_Dang_Nhap, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ten_Dang_Nhap, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mat_Khau, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mat_Khau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mat_Khau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <h4 id="thongbao">@ViewBag.ThongBao</h4>
                <h4 id="thongbao">@Session["thongbao"]</h4>
                <h4 id="thongbao">@Session["thongbaoreset"]</h4>
                <input type="submit" value="Đăng nhập" class="btn btn-default" />
                <a href="/TaiKhoan/QuenMatKhau">  Quên mật khẩu ?</a>
            </div>
        </div>
    </div>
}

<div>
    <a href="/Home/Index">Trở về</a>
</div>

QL_Tour_Du_Lich/QL_Tour_Du_Lich/Views/TaiKhoan/QuenMatKhau.cshtml
@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    #tuade{
        text-align:center;
    }
    #thongbao{
        color:red;
    }
</style>
<h2 id="tuade">Quên mật khẩu</h2>
<hr />
@using (Html.BeginForm("QuenMatKhau", "TaiKhoan", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col-md-2">
                Nhập địa chỉ email đã đăng ký: 
            </div>
            <div class="col-md-10">
                <input type="email" name="emailaddress" value=""/>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <h4 id="thongbao">@ViewBag.ThongBao</h4>
                <input type="submit" value="Lấy mật khẩu" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Trở về", "DangNhap")
</div>

QL_Tour_Du_Lich/QL_Tour_Du_Lich/Views/TaiKhoan/XacNhan.cshtml
@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    #tuade{
        text-align:center;
    }
    #thongbao{
        color:red;
    }
</style>
<h2 id="tuade">Xác nhận</h2>
<hr />
@using (Html.BeginForm("XacNhan", "TaiKhoan", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col-md-2">
                Nhập mã xác nhận: 
            </div>
            <div class="col-md-10">
                <input type="text" name="xacnhan" value="" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <h4 id="thongbao">@ViewBag.ThongBao</h4>
                <h4 id="thongbao">@Session["thongbao"]</h4>
                <input type="submit" value="@Session["ValueButton"]" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Trở về", "DangNhap")
</div>